---
- name: Скачиваем дистрибутив Vector
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    dest: "./vector-{{ vector_version }}.dpkg"

- name: Установка пакетов Vector
  become: true
  ansible.builtin.apt:
    deb: ./vector-{{ vector_version }}.dpkg
  notify: Перезапуск Vector
